server {
    listen 80;
    server_name hericarealtor.test;

    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass hericarealtor:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    location ~* \.(?:png|jpe?g|gif|ico|svg|webp|css|js|woff2?|ttf)$ {
        try_files $uri =404;
        access_log off;
        expires 1y;
    }

    location /storage/ {
        alias /var/www/storage/app/public/;
        try_files $uri =404;
    }
}
