server {
    listen 80;
    server_name portainer.justgui.test;
    resolver 127.0.0.11 valid=10s;
    set $upstream portainer:9000;
    location / {
        proxy_pass         http://$upstream;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
    }
}
